# PPO
# Curiosity strength: 0.001, gamma: 0.995
# Notes: ...

# https://unity-technologies.github.io/ml-agents/Training-Configuration-File/#extrinsic-rewards
engine_settings:
  time_scale: 1 # in game time scale, 1 means real time (for the purpose of physics simulation keep it 1)
behaviors:
  Hider:
    # !!! DEFAULT VALUES for ppo trainer, in order to make tests more reliable, we must keep the same values !!!
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      deterministic: False
      goal_conditioning_type: hyper
    # !!! END OF DEFAULT VALUES !!!

    # REWARD SIGNALS - more info: https://github.com/yosider/ml-agents-1/blob/master/docs/Reward-Signals.md
    reward_signals:
      extrinsic:
        gamma: 1.0
        strength: 1.0

      # intrinsic rewards - curiosity
      curiosity:
        gamma: 0.8 # typicall range 0.8 - 0.995
        strength: 0.01 # typicall range 0.001 - 0.1
        network_settings:
          normalize: True
          hidden_units: 128
          num_layers: 3
          goal_conditioning_type: hyper
          deterministic: False
  Seeker:
    # !!! DEFAULT VALUES for ppo trainer, in order to make tests more reliable, we must keep the same values !!!
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      deterministic: False
      goal_conditioning_type: hyper
    # !!! END OF DEFAULT VALUES !!!

    # REWARD SIGNALS - more info: https://github.com/yosider/ml-agents-1/blob/master/docs/Reward-Signals.md
    reward_signals:
      extrinsic:
        gamma: 1.0
        strength: 1.0

      # intrinsic rewards - curiosity
      curiosity:
        gamma: 0.8 # typicall range 0.8 - 0.995
        strength: 0.01 # typicall range 0.001 - 0.1
        network_settings:
          normalize: True
          hidden_units: 128
          num_layers: 3
          goal_conditioning_type: hyper
          deterministic: False

    max_steps: 1000000000 # 1 000 000 000
    time_horizon: 64 # 64
    summary_freq: 50000 # 50 000
    threaded: True
